# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller ONE-FOLDER build of the Vibenative desktop shell -> dist/Vibe Identify/.

Why onedir, not onefile:
  * onefile re-extracts the entire bundle (CPython + onnxruntime/DirectML DLLs,
    hundreds of MB of native code) into a temp dir on EVERY launch -> slow cold
    start and pointless disk churn. onedir keeps those DLLs resident.
  * the app resolves models/ and ffmpeg EXE-ADJACENT (loose files next to the exe).
    With onefile the running exe lives in a random temp dir, so "next to the exe"
    is not the folder the user sees -> resource resolution breaks. onedir gives a
    stable folder where models/ + ffmpeg.exe sit beside the exe.
  * onedir is patchable in place: swap in new models or a newer ffmpeg without a
    rebuild.

The ONNX models and ffmpeg are NOT baked into the bundle; tools/prepare_dist.py
copies them in beside the exe after the build (see tools/build_exe.py).

Build:  python tools/build_exe.py       (preferred: builds + copies models/ffmpeg)
   or:  pyinstaller "Vibe Identify.spec"  (bundle only)
"""

import os

from PyInstaller.utils.hooks import (
    collect_all,
    collect_data_files,
    collect_dynamic_libs,
    collect_submodules,
)

PROJECT = os.path.abspath(os.getcwd())  # PyInstaller runs the spec from the repo root
SRC = os.path.join(PROJECT, "src")  # src-layout: the importable `vibenative` package root

# --- vibenative: Flask templates + static assets must ship as bundle data -------
datas = collect_data_files("vibenative")  # templates/*.html + static/* (non-.py files)
# the in-app Guide reads docs/USAGE.md -> bundle it (resolved via paths.resource_base())
datas += [(os.path.join(PROJECT, "docs", "USAGE.md"), "docs")]
hiddenimports = collect_submodules("vibenative")  # routes.* / db / engine modules (lazy imports)

# --- onnxruntime native libraries, INCLUDING the DirectML EP --------------------
# collect_dynamic_libs pulls capi/*.dll: onnxruntime.dll, onnxruntime_providers_shared.dll,
# and crucially DirectML.dll (the GPU execution provider). We also collect_all so the
# package's own data/submodules come along.
ort_datas, ort_binaries, ort_hidden = collect_all("onnxruntime")
binaries = list(ort_binaries) + collect_dynamic_libs("onnxruntime")
datas += ort_datas
hiddenimports += ort_hidden

# Belt-and-braces: explicitly add every capi DLL by path so DirectML.dll can never be
# silently dropped by a hook change (the whole GPU story depends on it).
try:
    import onnxruntime as _ort

    _capi = os.path.join(os.path.dirname(_ort.__file__), "capi")
    for _f in os.listdir(_capi):
        if _f.lower().endswith(".dll"):
            binaries.append((os.path.join(_capi, _f), os.path.join("onnxruntime", "capi")))
except Exception:  # pragma: no cover - build-time best effort
    pass

# --- pywebview (Windows: winforms/edgechromium via pythonnet/clr) ---------------
wv_datas, wv_binaries, wv_hidden = collect_all("webview")
datas += wv_datas
binaries += wv_binaries
hiddenimports += wv_hidden
hiddenimports += [
    "webview.platforms.winforms",
    "webview.platforms.edgechromium",
    "clr",
    "flask",
    "jinja2",
    "mutagen",
]

# Optional app icon (generated by tools/prepare_dist.py or dropped in by hand).
_icon = os.path.join(PROJECT, "desktop", "vibe.ico")
icon = _icon if os.path.isfile(_icon) else None

a = Analysis(
    [os.path.join(PROJECT, "desktop", "genre_app.pyw")],
    pathex=[SRC, PROJECT],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # heavy things that are never imported at runtime -> keep the bundle lean
        "tensorflow",
        "tf2onnx",
        "matplotlib",
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "tkinter",
        "pytest",
        "IPython",
        "notebook",
        "scipy",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,  # onedir: binaries live beside the exe, not inside it
    name="Vibe Identify",
    debug=False,
    strip=False,
    upx=False,  # UPX corrupts some native DLLs (onnxruntime); never compress here
    console=False,  # --windowed: no console window
    icon=icon,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Vibe Identify",  # -> dist/Vibe Identify/
)
